#!/bin/sh
set -e

generate_filename() {
    echo "$1.png" | tr ' ' '_' | tr -d ':!?' | tr '[:upper:]' '[:lower:]'
}

create_sprite() {
    text="$1"
    dpi="${2:-150}"
    margin="${3:-1}"
    filename="${4:-$(generate_filename "$text")}"
    pango-view --background=transparent --dpi=$dpi --margin=$margin -qo "$filename" <(echo "$text")
    # extract the alpha channel
    magick "$filename" -alpha extract -strip "$filename"
    echo "Created $filename"
}

mkdir -p app/src/main/assets/sprites
cd app/src/main/assets/sprites

create_sprite 'Tiny Tic Tac Toe' 240
create_sprite 'has won!'
create_sprite 'Draw'
create_sprite 'Next turn:'
create_sprite 'Level:' 240
create_sprite 'Very easy'
create_sprite 'Easy'
create_sprite 'Medium'
create_sprite 'Hard'
create_sprite 'Very hard'

for i in $(seq 0 9); do
    create_sprite "$i"
done
